

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "3000:80"  # Nginx serves on 80
    depends_on:
      - backend
