

services:

  db:
    image: postgres:17
    env_file:
      -  ./backend/.env  # Load environment variables from .env file
    ports:
      - "5433:5432"  # Map host port 5433 to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: adminer_cv_matcher
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
        - db
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - ./backend:/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "3000:80"  # Nginx serves on 80
    depends_on:
      - backend

volumes:
  postgres_data:  # Define a named volume for PostgreSQL data