# STEP 1: Build React app
FROM node:18 as build
WORKDIR /app

# Copy only package files to leverage Docker cache
COPY frontend/package.json frontend/package-lock.json ./

RUN npm install

# Copy the rest of the frontend code
COPY frontend/ ./

RUN npm run build

# STEP 2: Serve with Nginx
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
